#ifndef MYSQLPLUGIN_GLOBAL_H
#define MYSQLPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MYSQLPLUGIN_LIBRARY)
#  define MYSQLPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MYSQLPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MYSQLPLUGIN_GLOBAL_H
